### ISSUE TITLE
Request for support of chunks related to collision and physics

### ISSUE THREAD

**Issue by WeaselOnaStick** [Hampo/LuaP3DEditor#1]
Programmatically creating collision is currently not that easy. I wish appropriate classes and functions were added for the following chunks:

1. Collision Volume Owner
2. Collision Volume Owner Name
3. ~~Collision Oriented Bounding Box~~
    - Preferably with a simple create function that takes in Centre Vector and Rotation Matrix rows 
        - (even better if it could also accept euler rotation and silently convert it to Matrix)
4. ~~Collision Sphere~~
    - Preferably with a simple create function that takes in Centre Vector and Radius
5. Collision Cylinder
    - Preferably with a simple create function that takes in Flat End (bool), Radius and Half Length
6. ~~Collision Vector (Centre, Rotation Matrix X/Y/Z)~~
7. Collision Object Attribute
8. Collision Axis Aligned Bounding Box
9. ~~Physics Joint~~
10. ~~Physics Vector~~
11. ~~Physics Inertia Matrix~~

**Comment by Hampo** [comment]
I can't add these yet - but will do when I'm back home (roughly a week away)

**Comment by Hampo** [comment]
I just pushed a commit (1162fa8ebdf07d4b80e11a0f62bbb3e6e4f77ee5) that added a few of these:
- Added Physics Joint
- Added Physics Vector
- Added Physics Intertia Matrix
- Added Collision Oriented Bounding Box
- Added Collision Sphere
- Added Collision Vector

**Comment by Hampo** [comment]
I've now rewritten the entire system, and all chunks are supported. Issue complete.
